export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_ERRORS = 'GET_ERRORS'
export const YELLOWPAGES_POST = 'YELLOWPAGES_POST'
export const POST_ERROR = 'POST_ERROR'
export const GET_YELLOWPAGES_POST = 'GET_YELLOWPAGES_POST'
export const GET_PROFILE_POSTS = 'GET_PROFILE_POSTS'
export const GET_PROFILES = 'GET_PROFILES'
export const LOADING = 'LOADING'
export const GET_STATES = 'GET_STATES'
export const GET_TOWNS = 'GET_TOWNS'
export const PHOTO_DELETED = 'PHOTO_DELETED'
export const UPDATE_POST = 'UPDATE_POST'
export const POST_QUESTION = 'POST_QUESTION'
export const QUESTION_ERROR = 'QUESTION_ERROR'
export const GET_QUESTIONS = 'GET_QUESTIONS'
export const VIEW_SIZE_UPDATED = 'VIEW_SIZE_UPDATED'
export const GET_RANDOM_POSTS = 'GET_RANDOM_POSTS'
export const GET_POPULAR_QUESTIONS = 'GET_POPULAR_QUESTIONS'
export const POST_ANSWER = 'POST_ANSWER'
export const VERIFY_USER = 'VERIFY_USER'
export const GET_PROFILE_QUESTIONS = 'GET_PROFILE_QUESTIONS'
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING'
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS'
export const QUESTION_FETCHING_FINISHED = 'QUESTION_FETCHING_FINISHED'
export const STOP_LOADING = 'STOP_LOADING'
export const CLEAR_YELLOWPAGES = 'CLEAR_YELLOWPAGES'
export const UPDATE_POSITION = 'UPDATE_POSITION'
export const GET_SPECIFIC_YELLOWPAGE = 'GET_SPECIFIC_YELLOWPAGE'
export const STOP_YELLOWPAGES_FETCHING_ONMOUNT = 'STOP_YELLOWPAGES_FETCHING_ONMOUNT'
export const YELLOWPAGES_FETCHING_FINISHED = 'YELLOWPAGES_FETCHING_FINISHED'
export const GET_SPECIFIC_QUESTION = 'GET_SPECIFIC_QUESTION'
export const STOP_COMPONENT_RELOAD = 'STOP_COMPONENT_RELOAD'
export const RESTORE_COMPONENT_RELOAD = 'RESTORE_COMPONENT_RELOAD'
export const CLEAR__SPECIFIC_QUESTIONS = 'CLEAR__SPECIFIC_QUESTIONS'
export const CLEAR_POST = 'CLEAR_POST'
export const DELETE_QUESTION = 'DELETE_QUESTION'
export const SET_QUERY = 'SET_QUERY'
export const RESET_QUESTIONS = 'RESET_QUESTIONS'
export const UPDATE_YELLOWPAGES_POSITION = 'UPDATE_YELLOWPAGES_POSITION'
export const STOP_QUESTION_FETCHING_ONMOUNT = 'STOP_QUESTION_FETCHING_ONMOUNT'

























